"""Update User model

Revision ID: 8aba6f38e2fa
Revises: c348e1b88b42
Create Date: 2026-06-30 10:19:29.870956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aba6f38e2fa'
down_revision: Union[str, Sequence[str], None] = 'c348e1b88b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription', if_exists=True)
    op.drop_table('transformation', if_exists=True)
    op.drop_table('stylistconversation', if_exists=True)
    op.drop_index(op.f('ix_user_age'), table_name='user', if_exists=True)
    op.drop_index(op.f('ix_user_email'), table_name='user', if_exists=True)
    op.drop_table('user', if_exists=True)
    op.drop_table('photo', if_exists=True)
    op.drop_table('glowupplan', if_exists=True)
    op.drop_table('stylistmessage', if_exists=True)
    op.drop_table('job', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('job_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_pkey'))
    )
    op.create_table('stylistmessage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['stylistconversation.id'], name=op.f('stylistmessage_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stylistmessage_pkey'))
    )
    op.create_table('glowupplan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('glowupplan_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('glowupplan_pkey'))
    )
    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('public_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('photo_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_table('stylistconversation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('stylistconversation_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stylistconversation_pkey'))
    )
    op.create_table('transformation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', postgresql.ENUM('VIRTUAL_TRY_ON', 'OUTFIT_RECOMMENDATION', 'COLOR_ANALYSIS', 'HAIR_STUDIO', 'MAKEUP_STUDIO', 'ACCESSORIES', 'OUTFIT_COMPLETION', 'PROFESSIONAL_PHOTOS', name='transformationcategory'), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('transformation_job_id_fkey')),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('transformation_photo_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('transformation_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transformation_pkey'))
    )
    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('provider_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('subscription_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_pkey'))
    )
    # ### end Alembic commands ###
