"""Create tool column and update output type

Revision ID: d9da97331454
Revises: ab3f75f54220
Create Date: 2026-07-10 15:20:22.970608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9da97331454'
down_revision: Union[str, Sequence[str], None] = 'ab3f75f54220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "job",
    sa.Column(
        "tool",
        sa.Enum("PORTRAIT", name="tool"),
        nullable=False,
        server_default="PORTRAIT",
    ),
    )
    op.alter_column(
        "job",
        "tool",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("job", "tool")
    
